require 'minitest-activemodel/version'

require 'minitest/matchers'
require 'minitest-activemodel/matchers/validation_matcher.rb'
require 'minitest-activemodel/matchers/validate_acceptance_matcher'
require 'minitest-activemodel/matchers/validate_confirmation_matcher'
require 'minitest-activemodel/matchers/validate_format_matcher'
require 'minitest-activemodel/matchers/validate_length_matcher'
require 'minitest-activemodel/matchers/validate_presence_matcher'
require 'minitest-activemodel/matchers/validate_uniqueness_matcher'
